apiVersion: apps/v1
kind: Deployment
metadata:
  name: code
  labels:
    app: code
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code
  template:
    metadata:
      labels:
        app: code
    spec:
      containers:
      - name: application
        image: repo.treescale.com/miquelbar/code:{{BUILD_ID}}
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: APM_NAME
          value: "bootcamp"
        - name: ELASTIC_APM_SERVER_URL
          value: http://apm.services
      imagePullSecrets:
      - name: regcred