apiVersion: apps/v1
kind: Deployment
metadata:
  name: code
  labels:
    app: code
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code
  template:
    metadata:
      labels:
        app: code
    spec:
      containers:
      - name: application
        image: cloud.canister.io:5000/miquelbar/code:{{BUILD_ID}}
        ports:
        - containerPort: 8080
          name: http
      imagePullSecrets:
      - name: regcred